name: Sync Fork

on:
  workflow_dispatch: # on button click
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          base: master
          head: master
          merge_method: rebase
